import fs from 'node:fs/promises';
import path from 'node:path';

// Use the same text, positions, table and image as the editable PowerPoint.
// slides.md is generated by build.mjs; do not maintain a second copy of the content.
const escape = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const box = e => `left:${e.x}px;top:${e.y}px;width:${e.w}px;height:${e.h}px`;
function element(e) {
  if (e.kind === 'image') return `<img class="work-image" src="${e.src}" alt="${escape(e.alt)}" style="${box(e)}" />`;
  if (e.kind === 'table') {
    const cols=e.widths.map(w=>`<col style="width:${w}px" />`).join('');
    const rows=e.rows.map((row,r)=>`<tr>${row.map((value,c)=>`<${r===0?'th':'td'} class="${c===0?'row-label':''}">${escape(value)}</${r===0?'th':'td'}>`).join('')}</tr>`).join('');
    return `<table class="work-table" style="${box(e)}"><colgroup>${cols}</colgroup><tbody>${rows}</tbody></table>`;
  }
  const style=`${box(e)};font-size:${e.size}px;color:${e.color};font-weight:${e.bold?700:400};font-family:'${e.font}','Noto Sans CJK JP','Meiryo',sans-serif;line-height:${e.lineSpacing}`;
  const content=escape(e.text).replaceAll('\n','<br>');
  return e.url ? `<a class="work-text" href="${escape(e.url)}" style="${style}">${content}</a>` : `<div class="work-text" style="${style}">${content}</div>`;
}
export async function exportSlidev(deckDir,slides) {
  const frontmatter=`---\ntheme: default\nlayout: none\ntitle: 公開されているAgent Skillsを使ってみる\ninfo: grill-meの紹介\ncanvasWidth: 1280\naspectRatio: 16/9\nfonts:\n  sans: Noto Sans JP\n  mono: DejaVu Sans Mono\n  local: Noto Sans JP, DejaVu Sans Mono\ntransition: none\nmdc: true\n---\n`;
  const pages=slides.map(s=>`<div class="work-slide" style="background:${s.background}">\n${s.elements.map(element).join('\n')}\n</div>\n\n<!--\n${s.notes.replaceAll('-->','--&gt;')}\n-->\n`);
  await fs.writeFile(path.join(deckDir,'slides.md'),frontmatter+'\n'+pages.join('\n---\nlayout: none\n---\n\n'));
}
